export const sampleImages = {
  hero: "https://framerusercontent.com/images/rCYE8FEyC5lN6m5coOuFOOgDJ8A.jpeg?scale-down-to=2048",
  editorial: "https://framerusercontent.com/images/vJzsJOlbUK8qkA5xxZA18jSC6SI.jpeg?scale-down-to=2048",
  brands: "https://framerusercontent.com/images/wxArQEjlcrBYFF8tdvyrSDA68Zw.jpeg?scale-down-to=2048",
  collectionLiving: "https://framerusercontent.com/images/h8rMLidvtxgO37bgs0urvbSKFOk.jpeg?scale-down-to=2048",
  collectionDining: "https://framerusercontent.com/images/AkcINRgdRJWagCIMhlfAa6SCpcs.jpeg?scale-down-to=2048",
  collectionBedroom: "https://framerusercontent.com/images/bzAxUIZb76NAbMbbTCNRKvwep8.jpeg?scale-down-to=2048",
  collectionLounge: "https://framerusercontent.com/images/rZjzFX7RCkgqdY9yyhbi4hs.jpeg?scale-down-to=2048",
  collectionAccent: "https://framerusercontent.com/images/5SmAeNVODUEpPeB9LOhC2baAXP4.jpeg?scale-down-to=2048",
  collectionStudio: "https://framerusercontent.com/images/VfSDa1aOzvtIWAcGV6dtAprgM.jpeg?scale-down-to=2048",
  journalA: "https://framerusercontent.com/images/I1KebQoYSXcDwvUsFzZRi0wIxE.jpeg?scale-down-to=2048",
  journalB: "https://framerusercontent.com/images/Uv9jeirMiBGocQPSDko8jsMMolo.jpeg?scale-down-to=2048",
  journalC: "https://framerusercontent.com/images/nYgQL26JA1Ioq4xVHJRlasIEC6Y.jpeg?scale-down-to=2048",
  founder: "https://framerusercontent.com/images/rCYE8FEyC5lN6m5coOuFOOgDJ8A.jpeg?scale-down-to=2048",
  space: "https://framerusercontent.com/images/VfSDa1aOzvtIWAcGV6dtAprgM.jpeg?scale-down-to=2048",
};
